### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by justinmchase** [guybedford/wasm-stdlib-hack#1]
Do you have an example of how I might use this? I'm assuming I would need to compile this to a module then provide it as an import into another module, both sharing the same memory?

Also is the dist published anywhere, or how would you recommend publishing this from my own app? Might be good to publish the original license into the dist folder too.

**Comment by ponchofiesta** [comment]
Not sure if this is the correct way without issues. But this works for me using a Go WASM module and this memory library:

```javascript
const go = new window.Go();
const memory = new WebAssembly.Memory({initial: 1024});

Promise.all([
    WebAssembly.instantiateStreaming(fetch('some-go-wasm-module.wasm'), {
        env: {memory},
        ...go.importObject
    }),
    WebAssembly.instantiateStreaming(fetch("memory.wasm"), {
        env: {memory}
    })
])
    .then(module => {
        go.run(module[0].instance);
        window.wasm.memHelper = {
            memory,
            ...module[1].instance.exports
        };
    });
```

**Comment by justinmchase** [comment]
Yeah I managed to figure it out also, the trick was setting a memory module into an import as "env: { memory }" as you said and then this imports. 

Then in your own library you can import:
```wat
(module
  (import "env" "memory" (memory 1))
  (import "stdlib" "malloc" (func $malloc (param i32) (result i32)))
  (import "stdlib" "free" (func $free (param i32)))
  (import "stdlib" "memcpy" (func $memcpy (param i32 i32 i32) (result i32)))

  ...
)
```
